smalldrop:
  module1:
    section2:
      param1:
        - 0
        - 0
        - 0
        - -1.571
        - 0
        - 1.571
        - 0.785
    section1:
      param3: string
      param2: 5.3
      param1: 10
  module2:
    section1:
      param1:
        - 1
        - 1
        - 2
        - 3
        - 5
      param2:
        - str1
        - str2
        - str3
  bioprint:
    section1:
      param4: 1.002300
      param6:
        - 1.231000
        - 2343.233000
        - 1124.200000
        - 1.232350
      param1:
        - 10
        - 100
        - 1000
        - 10000
        - 100000
      param5: bioprinting
      param2:
        - what
        - do
        - you
        - mean
        - test?
      param3: 1000